# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Funky Scout' do

end

target 'Funky ScoutTests' do

end

target 'Funky ScoutUITests' do

end

